---
- hosts: "manager"
  become: true
  roles:
  - docker
  - soft
  tasks:
    - name: ping_serv
      ping:
    
    - name: Adding user "{{ USERNAME }}" to docker group
      user:
        name: "{{ USERNAME }}"
        groups: "docker"
        append: "yes"

  vars:
    USERNAME: "vagrant"
