Vagrant.configure(2) do |config|
  config.vm.box = "hybytes/ubuntu-20.04-gui"
  config.vm.box_check_update = false

  config.vm.define "shcool" do |shcool|
    shcool.vm.network  "private_network", ip: "192.168.56.3", bridge: "enp44s0"
    shcool.vm.hostname = "shcool"
    shcool.vm.provider "virtualbox" do |vb|
       vb.memory = "6000"
       vb.cpus=4  
       vb.gui = true
       vb.name = "shcool"
       end
  end

end
